### ISSUE TITLE
Alt tags

### ISSUE THREAD

**Issue by siddhiijain** [sanjayV/ng-image-slider#10]
Cannot find the alt tag in this package?

**Comment by sanjayRanosys** [comment]
Hi @siddhiijain 

can you describe more what exact issue are you facing?
Are you want to add **alt tag** on slider images OR something else?

**Comment by siddhiijain** [comment]
Yes I want to add alt tag and I am not finding the option .

**Comment by sanjayV** [comment]
Hi @siddhiijain 
I will add this feature for you in next version.

**Comment by siddhiijain** [comment]
Ok Thanq

**Comment by sanjayV** [comment]
Hi @siddhiijain 
I have added functionality for add **alt** and **title** in image tag.
You just need to provide **alt** and **title** keys in _ImageObject_ .
_(**Note**: these both keys are optional.)_

For example : 
```
imageObject: Array<object> = [{
        image: 'assets/img/slider/2.jpg',
        thumbImage: 'assets/img/slider/2_min.jpeg',
        title: 'Image title',
        alt: 'Image alt'
    },
    ....
];
```
for more info please visit [link](https://www.npmjs.com/package/ng-image-slider)
