### ISSUE TITLE
Make available images set loading="lazy"

### ISSUE THREAD

**Issue by zy2ba** [sanjayV/ng-image-slider#108]
Currently in most browsers available to use loading="lazy" to activate lazy loading. Please create options to set this attribute for slider images. 
https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes

**Comment by sanjayV** [comment]
Hi @zy2ba 
Thanks for this suggestion
I have added lazy loading option in ng-image-slider version [2.8.0](https://www.npmjs.com/package/ng-image-slider)
