### ISSUE TITLE
Using base64 string to display the image, in preview getting "Invalid File Format" in HTML

### ISSUE THREAD

**Issue by sudhakar-sekar** [sanjayV/ng-image-slider#12]
@sanjayV 

This is the awesome package found to display both image and videos. 
I'm using base64 image string to display the image or video in my angular 7 project. In slider am able to view the image.
When I click the image and in preview the image is not displaying and spinner only loading, please check the below image.

![image](https://user-images.githubusercontent.com/29774378/60600960-d2fb0200-9dce-11e9-824d-836ee204d34a.png)

I have checked in HTML, i found the below tags,
```
<div class="lightbox-wrapper">
<a class="close">×</a>
<div class="lightbox-div">
<div class="pre-loader">
<div class="mnml-spinner"></div>
</div><div dir="ltr" class="ng-star-inserted">Invalid file format</div>
<a class="prev icons prev-icon disable" ng-reflect-klass="prev icons prev-icon" ng-reflect-ng-class="[object Object]">‹</a><a class="next icons next-icon" ng-reflect-klass="next icons next-icon" ng-reflect-ng-class="[object Object]">›</a></div></div>
```

My image object is like below,
imageObject: Array<object> = [{
        image: 'data:image/jpeg;base64,' + {{base64String}},
        thumbImage: 'data:image/jpeg;base64,' + {{base64String}},
        alt: 'Image',
        title: 'Image'
    }
];

Anyone help me to fix these, i need to fix it ASAP.

Thanks,
Sudhakar.

**Comment by sanjayV** [comment]
Hi @sudhakar-sekar 
Current version of **ng-image-slider** not support **base64Image** .
But I can update it for you in next version.

**Comment by sudhakar-sekar** [comment]
@sanjayV 
Thanks for the response. can you please add support for base64 string for image/video both ASAP.
I am waiting for next version release.

Thanks,
Sudhakar.

**Comment by sanjayV** [comment]
Hi @sudhakar-sekar 
Added this functionality in new version [@1.3.4](https://www.npmjs.com/package/ng-image-slider)

**Comment by sudhakar-sekar** [comment]
Hi @sanjayV,

Thanks for the immediate fix and it's working fine.
Awesome package to display the images and videos.

**Comment by sanjayV** [comment]
Hi @sudhakar-sekar 
if you really like this package then you can press **Star** for this package ;) :P

**Comment by sudhakar-sekar** [comment]
@sanjayV 
Done.

**Comment by sudhakar-sekar** [comment]
@sanjayV 
base64 video string is not working, video format mp4 only.

Will you please try to fix ASAP.

**Comment by sanjayV** [comment]
@sudhakar-sekar 
It not good idea to convert large amount data into base64 string. 
If you will try to convert mp4 to base64 string and use that string into browser, your browser will get hang for some time or it will not show relative video

So my suggestion is, you should use mp4 file path in slider insteadof mp4 base64 string.

**Comment by sudhakar-sekar** [comment]
@sanjayV 
I got that, but I want to do that. Try to add that feature also.
For displaying image and video using base64 string, that's the reason I chooses this package. Help me to achieve this one.

**Comment by sanjayV** [comment]
@sudhakar-sekar 
added video base64 feature in version **@1.3.5**

**Comment by sudhakar-sekar** [comment]
Thanks @sanjayV.
