### ISSUE TITLE
[Bug] Dynamically updating the images array doesn't display the first object of the new array.

### ISSUE THREAD

**Issue by usersina** [sanjayV/ng-image-slider#129]
In `app.component.ts` I have the following:
```JAVASCRIPT
videosList1: Array<object> = [
    {
      video: 'https://youtu.be/pVE92TNDwUk',
    },
    {
      video: 'https://youtu.be/hnp1pt8biD4',
    },
    {
      video: 'https://youtu.be/NpEaa2P7qZI',
    },
  ];

videosList2: Array<object> = [
    {
      video: 'https://youtu.be/pVE92TNDwUk', // This video will not be displayed
    },
    {
      video: 'https://youtu.be/iGpuQ0ioPrM',
    },
    {
      video: 'https://youtu.be/02uGbq-C_wo',
    },
  ];

  // The currently displayed list & an event to change it
  displayedVids = this.videosList1;
  onChangeList(): void {
    this.displayedVids = this.videosList2;
  }
```

In `app.component.html` I have the following:
```HTML
<div style="height: 450px; width: 600px">
    <ng-image-slider
      [images]="displayedVids"
      [infinite]="true"
      [imageSize]="{ width: '100%', height: '450px' }"
      #nav
    ></ng-image-slider>
 </div>
<button (click)="onChangeList()">Click me to display the other videos list!</button>
```

A simple fix I found is to add an empty first item to the second list like this:
```JAVASCRIPT
videosList2: Array<object> = [
    {
      video: 'Since I\'m not displayed, make me anything' // Will NOT be displayed
    },
    {
      video: 'https://youtu.be/pVE92TNDwUk', // Will now be displayed
    },
    {
      video: 'https://youtu.be/iGpuQ0ioPrM',
    },
    {
      video: 'https://youtu.be/02uGbq-C_wo',
    },
  ];
```

Why does this happen & how to avoid it? The fix is kind of monkey patching.

**EDIT**: If I also switch back to the first displayed items, the first video in that array isn't visible anymore. I can't add an empty placeholder to it, since it is displayed by default.

**Comment by Guigeek973** [comment]
Hello i got the same problem, i didn't succeed to do this, it's been 2 days i try to 😢 I got many chapters to show and i want on chapter select change the ng-image-slider refresh or reload or recreate ? i don't know how to do this with the actual code.

**Comment by hieuntp2** [comment]
I have same problem. When I click to open lightbox, the firsst image still loading until I have press some button, or click next image.

**Comment by sanjayV** [comment]
Its working fine with dynamic Image Array.
working example : https://ng-image-slider-demo-qkk1t2.stackblitz.io/
