### ISSUE TITLE
Change class container to some other name ?

### ISSUE THREAD

**Issue by dota2Pro** [sanjayV/ng-image-slider#13]
Right now the structure that is populated is
```
<ng-image-slider>
<div class="ng-image-slider">
<div class="container">
```

If you use [bootstrap ](https://getbootstrap.com/)in the code you get styles applied from its [container ](https://www.w3schools.com/bootstrap/bootstrap_get_started.asp)class .

Is it possible to rename image-slider's library class to something else ?

**Comment by sanjayRanosys** [comment]
@dota2Pro sure I will update...
**can you suggest class name?**

**Comment by sanjayV** [comment]
Hi @dota2Pro 
I have updated class name in version @1.3.6
