### ISSUE TITLE
Avoid reloading images on sliding

### ISSUE THREAD

**Issue by zrjosser** [sanjayV/ng-image-slider#15]
Each time the image is changed the image is reloaded from the server, which causes unwanted bandwidth to be consumed ...

**Comment by sanjayV** [comment]
Hi @zrjosser 
Can you share your code or link so that I can understand it more...
Are you updating images in **image** array dynamically??

**Comment by sanjayV** [comment]
Hi @zrjosser 
I am not sure about it.. but I think it's browser behaviour.
If I render my page first time then all images comes with 200 status.
But If I call same image url then browser send request again but this time I receive 304 (Not Modified) status code in response.

[Response image](http://tinyurl.com/y2k94emz)

I found that if we use **Cache-Control: max-age** header on server then it will use cache data first.
I can not do that changes in current *ng-image-slider* code, but suggest you to try it.

**Comment by zrjosser** [comment]
Yes, was a browser behaviour, sorry...
