### ISSUE TITLE
Works correct but got this error in console

### ISSUE THREAD

**Issue by shiftDE** [sanjayV/ng-image-slider#16]
I used common image address for image and thumpImage and slider works correct but I have this error:

NgImageSliderComponent.html:10 ERROR TypeError: Cannot read property 'thumbImage' of undefined

**Comment by sanjayV** [comment]
Hi @shiftDE 
Just want to confirm, are you sending **thumbImage** in images list array?

like this =>

```
imageObject = [{
    image: 'assets/img/slider/5.jpg',
    thumbImage: 'assets/img/slider/5_min.jpeg', // thum-image url here
    title: 'image five'
},
{
    ...
}];
```

**Comment by shiftDE** [comment]
Yes, I’m sending image, thumbImage and title

**Comment by sanjayV** [comment]
@shiftDE It seems like you are not passing correct images array.I also checked it with different type values. It's not throwing any error. 
either it showing images (if I pass correct array) and showing nothing, blank div (if I pass invalid value)

**Comment by shiftDE** [comment]
I’m passing same image address to image for tumbImage
I have images without error but not for tumbImage

**Comment by sanjayV** [comment]
@shiftDE  it would help me, if you share image array that you using in **ng-image-slider**

**Comment by sanjayV** [comment]
New version working fine without issue.
Please create new one if face any issue in console.

**Comment by shiftDE** [comment]
Thanks for the update and follow this issue up, I will check it out
