### ISSUE TITLE
Support Angular 14

### ISSUE THREAD

**Issue by Hermholtz** [sanjayV/ng-image-slider#162]
Hi,

right now ng-image-slider complains heavily when trying to use it with Angular 14. It happens not only when installing this package, but also when doing any `npm install`, even with unrelated packages. Can we please kindly ask you to release an updated package that works with newer versions of Angular? Thank you very much in advance. 

```
 > npm install --save ng-image-slider
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: helloworld@1.0.0
npm ERR! Found: @angular/common@14.0.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.7" from ng-image-slider@3.0.1
npm ERR! node_modules/ng-image-slider
npm ERR!   ng-image-slider@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by ogarules** [comment]
same here, please and thank you

**Comment by sanjayV** [comment]
@Hermholtz @ogarules 
You can use latest version of [ng-image-slider](https://www.npmjs.com/package/ng-image-slider)

**Comment by Hermholtz** [comment]
@sanjayV thank you sir! It works like a charm (note that Angular 14.0.5 is the minimum required, maybe change that to 14.0.0?)

You may also want to add tags to respective commits so that it's not lost on which commits the major versions are based :)

Thanks again!
