### ISSUE TITLE
slider doesn't accept width and height in vh

### ISSUE THREAD

**Issue by dota2Pro** [sanjayV/ng-image-slider#17]
Slider seems to take only pixel values in width and height imageSize doesn't apply width or height when given in vh

```
         <ng-image-slider
            [imageSize]="{width: '5vh', height: '5vh'}"
            [showArrow]="false"
            [imagePopup]="false"
            (imageClick)="onImageClick($event)"
            [images]="imageObject"
            #nav></ng-image-slider>](url)
```

Also `main` class has a fixed height of  200px

**Comment by dpatanin** [comment]
Hi, what's the current status about this issue? I believe the latest commit on the responsive-issue branch was on the 11th Sep 2019, is it gonna be merged into master soon?

**Comment by dota2Pro** [comment]
> Hi, what's the current status about this issue? I believe the latest commit on the responsive-issue branch was on the 11th Sep 2019, is it gonna be merged into master soon?

Just see this https://stackoverflow.com/questions/53942415/image-carousel-in-angular-6/54001536#54001536

Its very easy to create a slider on your own https://stackblitz.com/edit/angular-slidercarousel?file=src%2Fapp%2Fslider%2Fslider.component.ts
