### ISSUE TITLE
Angular 15, autoSlide not working

### ISSUE THREAD

**Issue by vikingbr** [sanjayV/ng-image-slider#176]
Hello everyone.
Tried various configurations but autoSlide is not working for me in Angular version 15

I'll be waiting for news. For the moment I will continue to use it without autoSlide. Thanks for the component!

![image](https://user-images.githubusercontent.com/18409355/208997909-713ef91b-48e4-4546-9b73-4b3c5958c481.png)

**Comment by sanjayV** [comment]
@vikingbr `autoSlide` only works with `[infinite]=true`
here is working example: https://stackblitz.com/edit/angular-opit91?file=src%2Fapp%2Fapp.component.html
