### ISSUE TITLE
I am a similar situation for which the lightbox in a full screen does not suit me.

### ISSUE THREAD

**Issue by jayyren** [sanjayV/ng-image-slider#177]
@Ceddaerrix currently just overriding some styles in my angular component with lightbox. Unfortunately, realized that there isn't enough just customizing styles for my needs (eg; pagination dots), so the only way is to patch or extend current solution

**Comment by sanjayV** [comment]
@jayyren I am working on this
Creating new configuration by which you can set **fullScreen** mode true/false.
