### ISSUE TITLE
Lightbox closes instead of playing video

### ISSUE THREAD

**Issue by jakub-stejskal** [sanjayV/ng-image-slider#182]
Replication steps:

- Go to https://stackblitz.com/edit/ng-image-slider-video-demo
- Click a slide to open lightbox
- Click "Play" icon in the center of the videothumbnail to play video
- Observe that it closes the lightbox instead

Solution:
iframe { position:absolute; } seems to do the trick

**Comment by sanjayV** [comment]
Issue fixed in latest version [7.0.1](https://www.npmjs.com/package/ng-image-slider).
