### ISSUE TITLE
Alt and Title should be separated

### ISSUE THREAD

**Issue by dirk-jacobs** [sanjayV/ng-image-slider#183]
I would like to have an Alt (for SEO) but no Title on images.  This to avoid the popup's.  
This is currently not possible, if there is an alt, there is auto-magically a title as well.
Alt and Title are 2 different things, please keep them separated or make this configurable by means of a setting

**Comment by sanjayV** [comment]
@dirk-jacobs Fixes deployed in latest versoin [ng-image-slider](https://www.npmjs.com/package/ng-image-slider)
