### ISSUE TITLE
Navigation buttons shouldn't be rendered as an <a>

### ISSUE THREAD

**Issue by dirk-jacobs** [sanjayV/ng-image-slider#184]
SEO doesn't like this as this is kind of 'dummy-mismatched-anchor'  
Woulld be nice if this could be a simple <span> or <div> with the correct styling

**Comment by sanjayV** [comment]
@dirk-jacobs Fixes deployed in latest versoin [ng-image-slider](https://www.npmjs.com/package/ng-image-slider)
