### ISSUE TITLE
Slider slides few pixels to right on init

### ISSUE THREAD

**Issue by jakub-stejskal** [sanjayV/ng-image-slider#185]
When slider is initialized it moves `(this.imageMargin * 2)` pixels to the right, enabling left arrow button and making it seems like there are more images to the left.

Seems to be caused by this change:
https://github.com/sanjayV/ng-image-slider/commit/737ee3609be6b20b0b0b3d84f536722d862d8743

**Comment by pawelel** [comment]
Hi, there is similar issue:
![moving](https://github.com/sanjayV/ng-image-slider/assets/14290787/83b59b4c-d1eb-4bfc-8566-aba7676cfd8e)

**Comment by sanjayV** [comment]
@jakub-stejskal @pawelel Fixes deployed in latest versoin [ng-image-slider](https://www.npmjs.com/package/ng-image-slider)
