### ISSUE TITLE
Slider closes the full screen window when I click on the youtube video play button

### ISSUE THREAD

**Issue by Prognosticator** [sanjayV/ng-image-slider#186]
Hello,

I've been using ng-image-slider 6.0.0 for the last year for my project, and in my webpage I have 3 youtube videos in the slide followed by pictures. When I used to click on the slide, it used to play the youtube videos when I click on the red youtube play button, and everything worked fine.
Now that I upgraded my angular to 15.2.9, whenever I click on the youtube red button in the slider, it simply closes and doesnt play the youtube video. I do not see any error in the console, so I am unsure what is going on.

My site went live and this is a big issue that I need resolved as it is on the main page of the site. If you go to my site https://collectthe10s.com you will see the slider, and when you click on it, the youtube video will simply cause it to close.

I tried upgrading ng-image-slider to 7.0.0 but I still get the same issue.

**Comment by sehban-alam** [comment]
I am facing the same issue. I am on angular 15. And it is specifically happening with me on iOS using Chrome and Safari

**Comment by nielswhydonate** [comment]
Hi @sanjayV, any update on this issue?

Is there anything we can do to help resolve this bug? We are happy to think along for a possible solution. 

Best,
Niels

**Comment by sanjayV** [comment]
Issue fixed in latest version [7.0.1](https://www.npmjs.com/package/ng-image-slider).
