### ISSUE TITLE
Lightbox/Popup closes when we try to play YouTube Video on iOS+Chrome

### ISSUE THREAD

**Issue by sehban-alam** [sanjayV/ng-image-slider#187]
HI,

I have been using this package for a long time and recently it has started behaving strangely. When the user is on iOS + Chrome. And clicks on the video, the Lightbox/Popup opens with the Play button in the center. It auto-closes after clicking on the play button. 

Please note that it is not happening on Android+Chrome or Windows+Chrome, but only on iOS+Chrome and iOS+Safari.

This feature is quite important for us. Is there any way we can resolve it quickly?

**Comment by sanjayV** [comment]
@sehban-alam this issue already reported here #186 and I am working on it

**Comment by sanjayV** [comment]
Issue fixed in latest version [7.0.1](https://www.npmjs.com/package/ng-image-slider).
