### ISSUE TITLE
Video .mp4 not reproduced in safari IOS

### ISSUE THREAD

**Issue by marcosybarraa** [sanjayV/ng-image-slider#19]
Hi @sanjayV ,
thanks for your work in this useful project.
I am playing videos in format .mp4 working fine in chrome computer, chrome android devices but not in safari IOS in iphone. I have google a little and seems is a common problem that should be solved adding "type" param, I would suggest to have this as string input param in the module, ¿would be possible?

https://stackoverflow.com/questions/20347352/html5-video-tag-not-working-in-safari-iphone-and-ipad

Kind regards !

**Comment by sanjayV** [comment]
Hi @marcosybarraa 

I checked **ng-image-slider** demo in safari IOS iphone. It's working fine. MP4 video playing for me.
Only issue is that, it's not showing video default *poster-image* if we are not passing any poster image for video.

**Comment by marcosybarraa** [comment]
Hi @sanjayV ,
thanks for your reply. After some research more in detail from my side, I can confirm that problem was on my side with the .mp4 encoded in a profile not compatible with ios.
Kind regards
