### ISSUE TITLE
Angular 17 compatability

### ISSUE THREAD

**Issue by erwindemoel** [sanjayV/ng-image-slider#193]
Hi, we're very happily using your image slider. However it doesn't work on the latest version of Angular 17. Could you please update the project so we can keep using it?

**Comment by EphraimHaber** [comment]
I've opened a pull request,
you can go ahead and try it out by running
npm i ng-image-slider-v17
<img width="310" alt="image" src="https://github.com/sanjayV/ng-image-slider/assets/61934858/016fa93e-ee9a-45d6-8bd2-e169c1c244a6">
didn't change anything other then the deps. nor did I edit the README

**Comment by EphraimHaber** [comment]
#194

**Comment by mmorac** [comment]
Hi @EphraimHaber, I tried that, but still got this message, not sure if you can tell what's wrong:

![image](https://github.com/sanjayV/ng-image-slider/assets/36863532/0e7cdc39-0605-410f-b42b-dbbed5a9f0bc)

Can't tell where that @angular/common@15.0.4 comes from

**Comment by EphraimHaber** [comment]
Can you send your package.json>

**Comment by mgardi85** [comment]
Please share when can we expect a release stable version which supports Angular 17. The one shared above is coming from a different package name.
Can the same PR be merged.

**Comment by EphraimHaber** [comment]
@mmorac Try installing this
`npm i ng-image-slider-v17`

**Comment by mgardi85** [comment]
> @mmorac Try installing this `npm i ng-image-slider-v17`

yes I have tried that & it is working.
When we moved from Angular v15 to v16 , I also had a switch to using ng-image-slider-v16 .
However I do not feel this approach is a sustainable one. Instead why is the original package not publishing new version. I see both for v16 & v17 , new packages are created instead of bumping up versions of existing packages.  Angular v18 is coming up next week so are we expecting a new package **ng-image-slider-v18** then ?

**Comment by EphraimHaber** [comment]
@mgardi85 Correct. Ideally this PR should be accepted, if I'll make the time I can just publish it under a new name. That was just a quick hack since I needed this package to be angular 17 compatible ASAP

**Comment by MarcoWGC** [comment]
Hi all. Any plans for Angular 18? :-)

**Comment by EphraimHaber** [comment]
I can make it happen, I can pull off the unholy and make ng-image-slider-v17 be compatible with angular 18 lol @MarcoWGC

**Comment by sanjayV** [comment]
Added Angular 17+ support in latest [version 9](https://www.npmjs.com/package/ng-image-slider)
