### ISSUE TITLE
Ng Image Slider require Click to show the images otherwise It keep loading.

### ISSUE THREAD

**Issue by ziaKhan1995** [sanjayV/ng-image-slider#197]
I am opeing the slider using 

**this.slider?.showLightbox();** method

The problem is that it keep laoding untill I click somewhere. On click it show the images which are already laoded.
I have applied all techniques like this.cdr.detectchanges, applies maunual click to the image in slider or element in our html but it still require  my click on any part of the slider to show the images.
![image](https://github.com/sanjayV/ng-image-slider/assets/77499979/13b9297b-5651-4bd3-9a55-ed88410cdd9f)

**Comment by sanjayV** [comment]
@ziaKhan1995 Fixed issue in latest [version 9](https://www.npmjs.com/package/ng-image-slider)
