### ISSUE TITLE
Distance between images and limiting number of images visible

### ISSUE THREAD

**Issue by leocifer** [sanjayV/ng-image-slider#20]
Hey,

I was wondering whether there is a way to increase/decrease the distance between images.

Also, is there a way to set the number of images.

**Comment by sanjayV** [comment]
@leocifer 
**ng-image-slider** use 100% width of it parent element width. So you can set visible images limit by set parent element width.
You can check working example [demo here](https://sanjayv.github.io/ng-image-slider/)

and regarding distance between images: currently there is no option for set distance between images, **but in next version I will provide this option**.

**Comment by sanjayV** [comment]
Hi @leocifer 

Just published new version of *ng-image-slider*. Now you can set space between image by **imageSize** input option. 
`[imageSize]="{space: 10}"`

for more info check [link](https://www.npmjs.com/package/ng-image-slider#api-reference-optional-) 

As I already mentioned, you can set visible images limit by set parent element width. _(in which you rendered <ng-image-slider ... />)_ .
[Example](https://sanjayv.github.io/ng-image-slider/)

**Comment by sanjayV** [comment]
@leocifer hope you are able to add space between images now...
closing issue.
