### ISSUE TITLE
how to handle error event for image inside ng-image-slider 

### ISSUE THREAD

**Issue by ThisisSahilMujawar** [sanjayV/ng-image-slider#206]
I am using an ng-image-slider inside angular component to display sliding images. If the source of the image is not available then I want my slider to show default image (with taken into consideration that default image is definitely present). I have seen to handle such issues we use onerror event for <img> tag. so it would be (error) event handler in angular but how can I do that for an image inside ng-image-slider ? 
So how we can do it for images inside <ng-image-slider>

**Comment by sanjayV** [comment]
Hi @ThisisSahilMujawar 
May I know which version of ng-image-slider you are using?

**Comment by sanjayV** [comment]
Fixes deployed in [latest verson](https://www.npmjs.com/package/ng-image-slider/v/10.0.0) 
https://www.npmjs.com/package/ng-image-slider/v/10.0.0
