### ISSUE TITLE
Handling Image Load Errors with Fallback Image in ng-image-slider

### ISSUE THREAD

**Issue by JaisankarEIT** [sanjayV/ng-image-slider#207]
I am currently using the ng-image-slider component in my Angular application. However, I am facing an issue where images might fail to load (due to broken links, network issues, etc.), and I need a way to handle these errors and show a fallback image.?

**Comment by sanjayV** [comment]
Hi @JaisankarEIT 
May I know which version of ng-image-slider you are using?

**Comment by JaisankarEIT** [comment]
"ng-image-slider": "^7.0.1"

**Comment by JaisankarEIT** [comment]
> Hi @JaisankarEIT May I know which version of ng-image-slider you are using?

"ng-image-slider": "^7.0.1",

**Comment by sanjayV** [comment]
Fixes deployed [latest verson](https://www.npmjs.com/package/ng-image-slider/v/10.0.0) 
https://www.npmjs.com/package/ng-image-slider/v/10.0.0
