### ISSUE TITLE
Slider not visible without any console error 

### ISSUE THREAD

**Issue by KanhaKanha123** [sanjayV/ng-image-slider#21]
I have added all the necessary packages as per your docs but i am not able to render the slider on my page. When i inspect element i am having the below mentioned code . In your demo the structure is different. Please let me know what i am missing in it.
*------------------------------------------*

ng-image-slider _ngcontent-c31="" ng-reflect-images="[object Object],[object Object"><div class="ng-image-slider" ng-reflect-ng-style="[object Object]" style="height: 200px;"><div class="ng-image-slider-container"><div class="main" ng-reflect-ng-style="[object Object]" style="height: 200px;"><div class="main-inner ng-star-inserted" ng-reflect-klass="main-inner" ng-reflect-ng-class="[object Object]" ng-reflect-ng-style="[object Object]" style="margin-left: 0px; width: 844px; transition: all 1s ease-in-out 0s;"><div class="img-div image-popup ng-star-inserted" ng-reflect-klass="img-div" ng-reflect-ng-class="[object Object]" ng-reflect-ng-style="[object Object]" style="width: 205px; margin-left: 3px; margin-right: 3px;"><custom-img ng-reflect-image-url="../../assets/images/banner1.jp" ng-reflect-is-video="false" ng-reflect-alt="Image alt" ng-reflect-title="Image alt" ng-reflect-direction="ltr"><div class="ng-star-inserted"><img class="image ng-star-inserted" ng-reflect-ng-class="[object Object]" src="../../assets/images/banner1.jpg" alt="Image alt" title="Image alt"></div></custom-img></div><div class="img-div image-popup ng-star-inserted" ng-reflect-klass="img-div" ng-reflect-ng-class="[object Object]" ng-reflect-ng-style="[object Object]" style="width: 205px; margin-left: 3px; margin-right: 3px;"><custom-img ng-reflect-image-url="../../assets/images/banner1.jp" ng-reflect-is-video="false" ng-reflect-alt="Image alt" ng-reflect-title="Image alt" ng-reflect-direction="ltr"><div class="ng-star-inserted"><img class="image ng-star-inserted" ng-reflect-ng-class="[object Object]" src="../../assets/images/banner1.jpg" alt="Image alt" title="Image alt"></div></custom-img></div><div class="img-div image-popup ng-star-inserted" ng-reflect-klass="img-div" ng-reflect-ng-class="[object Object]" ng-reflect-ng-style="[object Object]" style="width: 205px; margin-left: 3px; margin-right: 3px;"><custom-img ng-reflect-image-url="../../assets/images/banner1.jp" ng-reflect-is-video="false" ng-reflect-alt="Image alt" ng-reflect-title="Image alt" ng-reflect-direction="ltr"><div class="ng-star-inserted"><img class="image ng-star-inserted" ng-reflect-ng-class="[object Object]" src="../../assets/images/banner1.jpg" alt="Image alt" title="Image alt"></div></custom-img></div><div class="img-div image-popup ng-star-inserted" ng-reflect-klass="img-div" ng-reflect-ng-class="[object Object]" ng-reflect-ng-style="[object Object]" style="width: 205px; margin-left: 3px; margin-right: 3px;"><custom-img ng-reflect-image-url="../../assets/images/banner1.jp" ng-reflect-is-video="false" ng-reflect-alt="Image alt" ng-reflect-title="Image alt" ng-reflect-direction="ltr"><div class="ng-star-inserted"><img class="image ng-star-inserted" ng-reflect-ng-class="[object Object]" src="../../assets/images/banner1.jpg" alt="Image alt" title="Image alt"></div></custom-img></div></div><a class="prev icons prev-icon disable ng-star-inserted" ng-reflect-klass="prev icons prev-icon" ng-reflect-ng-class="[object Object]">‹</a><a class="next icons next-icon ng-star-inserted" ng-reflect-klass="next icons next-icon" ng-reflect-ng-class="[object Object]">›</a></div></div></div></ng-image-slider
*-------------------------------------------------------*

Image array is 
ts file------------>
  public imageObject: Array<any> = [
{
  image: '../../assets/images/banner1.jpg',
    thumbImage: '../../assets/images/banner1.jpg',
    alt: 'Image alt'
},
{
  image: '../../assets/images/banner1.jpg',
    thumbImage: '../../assets/images/banner1.jpg',
    alt: 'Image alt'
},
{
  image: '../../assets/images/banner1.jpg',
    thumbImage: '../../assets/images/banner1.jpg',
    alt: 'Image alt'
},
{
  image: '../../assets/images/banner1.jpg',
    thumbImage: '../../assets/images/banner1.jpg',
    alt: 'Image alt'
}
];
HTML--->
  <ng-image-slider [images]="imageObject" #nav></ng-image-slider>

Imported inside app.module.ts also.----------->
import { NgImageSliderModule } from 'ng-image-slider';
@NgModule({
  imports: [
    NgImageSliderModule
  ],
is there any css file do we need to add?

**Comment by KanhaKanha123** [comment]
Please suggest me anything

**Comment by sanjayV** [comment]
Hi @KanhaKanha123 
can you confirm images urls are correct?

**Comment by KanhaKanha123** [comment]
Hello Sanjay i managed to render. I have a another question now. How can we attach data to image array and retreive on image click for example.  {
   	image: 'assets/img/slider/1.jpg',
       thumbImage: 'assets/img/slider/1_min.jpeg',
       alt: 'Image alt',
data:{id:2,src:'http;.mlmlm;l'
   }

**Comment by KanhaKanha123** [comment]
I think it would be great if you will update your component code to receive image object instead if index only.
 <div [ngClass]="{'image-popup': imagePopup}"
                    [ngStyle]="{'width':sliderImageWidth+'px', 'margin-left':imageMargin+'px', 'margin-right':imageMargin+'px'}"
                    class="img-div"
                    *ngFor="let img of imageObj; let i = index"
                    (click)="imageOnClick(i)"
                    (mouseenter)="imageMouseEnterHandler()"
                    (mouseleave)="imageAutoSlide()"
                    #imageDiv> 
Can you please do that?. mostly developer use full object so they can choose whatever they want. If there is an alternative way to this please suggest me that too.

Thanks

**Comment by sanjayV** [comment]
@KanhaKanha123 
Yes I can update code..
But you can also use same index for get data from array list that you already have ;)

**Comment by sanjayV** [comment]
`const currentData = this.imageObject[receivedIndexHere]`

**Comment by KanhaKanha123** [comment]
Thanks ,
Yes can get but that will be a extra task to apply filter again in array ;)

**Comment by KanhaKanha123** [comment]
library is good i appreciate your work. easy to understand

**Comment by KanhaKanha123** [comment]
in case of mp4 file the height is short compared with image. do you have any suggestion for that?

**Comment by sanjayV** [comment]
User **posterImage** for mp4 videos
```
{
       video: 'assets/video/movie2.mp4',
       posterImage: 'assets/img/slider/2_min.jpeg', // slider image for mp4 video 
       title: 'Image title'
}
```

**Comment by KanhaKanha123** [comment]
will it be fixed for all video files?

**Comment by KanhaKanha123** [comment]
actually i have used your code direct in my project as i was facing some issues. and i used the same url as posterImage and i put background gay for video. It looks good for me. But i think it's depends on requirements we may use a static image also for video.

**Comment by sanjayV** [comment]
> will it be fixed for all video files?

Hi @KanhaKanha123 one poster image will be use for one video
you need to set poster image for each mp4 video

```
const imagesArray = [
    {
       video: 'assets/video/movie1.mp4',
       posterImage: 'assets/img/slider/posterImgFor1.jpg', // slider image for mp4 video 
       title: 'Video 1 title'
    },
    {
       video: 'assets/video/movie2.mp4',
       posterImage: 'assets/img/slider/posterImgFor2.jpg', // slider image for mp4 video 
       title: 'Video 2 title'
    },
    ....
]
```
