### ISSUE TITLE
Open full-screen slider from custom image

### ISSUE THREAD

**Issue by marcosybarraa** [sanjayV/ng-image-slider#22]
Hi, I am taking a look at the examples and I dont see clear if is possible to use the nice full-screenview with swipe function but fire programmatically. 
IE: I have some images in a angular material card, and I would like to open the image in full screen using your lightbox when the user clicks on the image

<img 
          mat-card-image src="{{srcCamera}}" 
          (click)="openImageSliderLightbox(camera)">

¿Is this possible with the current module?

**Comment by sanjayV** [comment]
Hi @marcosybarraa 
You want to use only full-screen lightbox without image slider?

**Comment by sanjayV** [comment]
Hi @marcosybarraa 
I have created new npm package for **full screen view popup** only
[https://www.npmjs.com/package/ng-image-fullscreen-view](https://www.npmjs.com/package/ng-image-fullscreen-view)
