### ISSUE TITLE
Index issue using `imageClick` event

### ISSUE THREAD

**Issue by eralvarez** [sanjayV/ng-image-slider#23]
# Index issue using `imageClick` event

## Description
I have a slider with 3 images and custom `prev` and `next` buttons, but when I click in the image it always give me the same index position that it's shown in the slider.

## Target

`ng-image-slider` component

## Evidence:

**In all scenarios I'm doing click from left to right**

### First scenario:
Normal 3 images and when I click them it's working
![image](https://user-images.githubusercontent.com/12943375/67421215-e94aea80-f584-11e9-8199-52a340614066.png)

### Second scenario:
After doing click 2 times in the next button, now the first image is the 3rd one and the event still show the same index, in this picture the event gave me the index `1` to the image `#3` and it should be `3` or better, start with index `0`
![image](https://user-images.githubusercontent.com/12943375/67421308-0f708a80-f585-11e9-971e-e53d58fa87a7.png)

## Expected results
1. Give the correct index when user trigger `imageClick` event even if the user clicks in the next/prev custom buttons
2. index should start at 0, not 1

**Comment by sanjayV** [comment]
@eralvarez I have fixed index issue in new version [@2.2.0](https://www.npmjs.com/package/ng-image-slider)

**Comment by eralvarez** [comment]
@sanjayV Great, I'll test it in a chance, thnks!

**Comment by sanjayV** [comment]
@eralvarez can we close this issue if it is working fine for you now?

**Comment by shyne326** [comment]
Please I have an issue with ng-image-slider. What if I need an action to be taken on image hover and not on image click, how can I go about it ?
