### ISSUE TITLE
imageClick event index issue

### ISSUE THREAD

**Issue by metalllus** [sanjayV/ng-image-slider#24]
Hello, I am having trouble with the `imageClick` event index. If autoSlide option is on, upon image click, the event returns image index based on current image position in the carousel, NOT according to its position in the source array. This makes it impossible to determine which image in the source array was actually clicked because the index of the same image changes all the time according to its current position in the carousel. Could you please fix this?

**Comment by sanjayV** [comment]
Hi @metalllus I have fixed index issue in new version [@2.2.0](https://www.npmjs.com/package/ng-image-slider)

**Comment by sanjayV** [comment]
@metalllus  can we close this issue if it is working fine for you now?

**Comment by metalllus** [comment]
yes, thank you.
