### ISSUE TITLE
arrow left and arrow right key

### ISSUE THREAD

**Issue by mokhtar93** [sanjayV/ng-image-slider#25]
i wanna know how can i disable sliding from left arrow key and right arrow key on the keyboard?

**Comment by sanjayV** [comment]
@mokhtar93 this functionality not available in current version, but I will provide it to you soon in next version

**Comment by sanjayV** [comment]
@mokhtar93 
Added new *Input Decorators* **arrowKeyMove** for disable arrow key move event disable in version [2.3.0](https://www.npmjs.com/package/ng-image-slider)
you just need to set value as **false**.
```
<ng-image-slider 
    [images]="imageObject"
    [arrowKeyMove]="false"
    #nav>
</ng-image-slider>
```
