### ISSUE TITLE
Does it support video to play within the slides instead of popup window?

### ISSUE THREAD

**Issue by chinna-dev** [sanjayV/ng-image-slider#28]

**Comment by sanjayV** [comment]
no, slider showing video images and thumb images.

**Comment by hverma** [comment]
@sanjayV thanks for your great work! Is there a way to hide video controls (play, slidebar etc) when not expanded?

**Comment by hverma** [comment]
A simple hack has got be going but it will be great to have it as an option as it slower to manipulate don this way.

    let HTMLElement: HTMLVideoElement = this.el.nativeElement.querySelector(`.video`);
    HTMLElement.controls = false;

**Comment by sanjayV** [comment]
@hverma 
I will add this option in next version of **ng-image-slider**
You can  create separate issue for this.

**Comment by sanjayV** [comment]
@hverma 
I have added `showVideoControls` option for show/hide video controls in [ng-image-slider new version](https://www.npmjs.com/package/ng-image-slider#api-reference-optional-).

**Comment by hverma** [comment]
Great Thx @sanjayV
