### ISSUE TITLE
How to provide the number of images in  the slider?

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [sanjayV/ng-image-slider#3]
how to  provide number of images in slider?
Please provide one solution... thanks

**Comment by sanjayV** [comment]
@KSANTHOSHKUMA can you elaborate your question?

**Comment by KSANTHOSHKUMA** [comment]
please find below screen shot?

![image](https://user-images.githubusercontent.com/19944264/51073433-ceaf2100-1696-11e9-9fce-fa47904b8e97.png)


1. in the slider 5 images are there? but i need only 3 images
2. there is circle for left, right buttons in the slider , how to remove the circles for left, right buttons
3. i want to display SIP name on top of every image(as per our Application requiremet).
**Please provide solution for above 3 queries.....**

**Comment by sanjayV** [comment]
@KSANTHOSHKUMA 
1. in the slider 5 images are there? but i need only 3 images

> **ng-image-slider** is responsive image slider, it use 100% width of parent element. If you want to show only three images then you just need to set width of parent element.

```
<div style="width: 300px">
<ng-image-slider [images]="imageObject" (imageClick) = "getImageIndex($event)[imagePopup]="false"> </ng-image-slider>
</div>
```

2. there is circle for left, right buttons in the slider , how to remove the circles for left, right buttons

> you can overwrite **ng-image-slider** css by your own custom css. Just set following css code in your css file.

```
ng-image-slider .ng-image-slider .container .main .prev,
ng-image-slider .ng-image-slider .container .main .next {
    background: transparent !important;
}
```

3. i want to display SIP name on top of every image.

> I am working on same requirements. You can receive updates in next version (**1.0.7**)

**Comment by KSANTHOSHKUMA** [comment]
Thank you!!!!
