### ISSUE TITLE
Can't bind to 'sliderMainDivWidth' since it isn't a known property of 'ng-image-slider'.

### ISSUE THREAD

**Issue by pkmarathe** [sanjayV/ng-image-slider#30]
**Error**
compiler.js:2175 Uncaught Error: Template parse errors:
Can't bind to 'sliderMainDivWidth' since it isn't a known property of 'ng-image-slider'.
1. If 'sliderMainDivWidth' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ct" [showArrow]="true" [infinite]="true" [autoSlide]="1"
 [animationSpeed]="1" [imagePopup]="true"  [ERROR ->][sliderMainDivWidth]="500"
 (imageClick)="clickMe()" #success_stories_slider></ng-image-slider>
<div "): ng:///WMModule/SuccessStoriesComponent.html@1:43

**Template Code**
<ng-image-slider [images]="imageObject" [showArrow]="true" [infinite]="true" [autoSlide]="1"
 [animationSpeed]="1" [imagePopup]="true"  [sliderMainDivWidth]="500"
 (imageClick)="clickMe()" #success_stories_slider></ng-image-slider>

**Comment by sanjayV** [comment]
Yes, **sliderMainDivWidth** is not a property of **ng-image-slider**
Please refer following link for more detail
[ng-image-slider-doc](https://www.npmjs.com/package/ng-image-slider)

**Comment by pkmarathe** [comment]
Thanks for your prompt response. Could you please assist me how to set height & width for this ng-image-slider.
I am trying to set height and width ng-image-slider as below but its not working.

<ng-image-slider [images]="imageObject" [showArrow]="true" [infinite]="true" [autoSlide]="1"
 [animationSpeed]="1" [imagePopup]="true" style="width: 500px; height: 700px;"
 (imageClick)="imageOnClick($event)" #success_stories_slider></ng-image-slider>
