### ISSUE TITLE
how to apply multi-row property to image slider 

### ISSUE THREAD

**Issue by pkmarathe** [sanjayV/ng-image-slider#33]
how to apply multi-row image slider instead of singal row slider.

**Comment by sanjayV** [comment]
@pkmarathe can you describe more...
Do you want to show same slider in multiple rows
OR
Multiple slider in same page in multiple rows ?

**Comment by pkmarathe** [comment]
Thanks for your reply.
I am looking for single slider with multiple rows. Please see attached image.

![image](https://user-images.githubusercontent.com/45457172/73069222-dadada80-3eb5-11ea-93d4-58b1af2c7afb.png)

**Comment by sanjayV** [comment]
Hi @pkmarathe 
Current slider doesn't support multi row feature?
