### ISSUE TITLE
ImageSize

### ISSUE THREAD

**Issue by rlee1990** [sanjayV/ng-image-slider#34]
Hi is there a way to set the width to 100% for each image

**Comment by sanjayV** [comment]
Hi @rlee1990 
are you looking like this single image slider https://ng-image-slider.herokuapp.com/ ?

**Comment by rlee1990** [comment]
@sanjayV yes

**Comment by sanjayV** [comment]
Hi @rlee1990 
Please have a look working example
https://angular-dep6cc.stackblitz.io/
and code
https://stackblitz.com/edit/angular-dep6cc

**Comment by sanjayV** [comment]
@rlee1990 
I have pushed new version of [ng-image-slider](https://www.npmjs.com/package/ng-image-slider)
Now you can pass image **width 100%**
just pass widht: 100% in **imageSize** Input

Ex:

```
<ng-image-slider 
    [images]="imageObject" 
    [imageSize]="{width: '100%', height: '80%'}"
    #nav></ng-image-slider>
```

**Comment by sanjayV** [comment]
@rlee1990 can we close this issue if it's working fine for you?
