### ISSUE TITLE
window resize

### ISSUE THREAD

**Issue by gmareater** [sanjayV/ng-image-slider#35]
hi
thanx for your nice work :)

when slider is on screen if we resize windows or change the zoom, images inside slider does not escale with container
please look at the image, at start is working correctly, but as i said if zoom changes, this happend

![image](https://user-images.githubusercontent.com/6206777/73430454-5d9ae400-4353-11ea-949c-0d6f0e51cd6b.png)

**Comment by sanjayV** [comment]
@gmareater Can you verify same with below example?
https://sanjayv.github.io/ng-image-slider/

**Comment by gmareater** [comment]
hi
i tried, but i cant reproduce it 
i will try on my side to find exact situation, i let you know

**Comment by sanjayV** [comment]
Hi @gmareater 
I have published new version of [ng-image-slider](https://www.npmjs.com/package/ng-image-slider) 
Now you can pass image width or height in %

```
<ng-image-slider 
    [images]="imageObject" 
    [imageSize]="{width: '100%', height: '80%'}"
    #nav></ng-image-slider>
```

Hope it will resolve your issue.

**Comment by gmareater** [comment]
thanx for your support, i will update tonight.

that's how people should support their works :)
well done bro

**Comment by gmareater** [comment]
one another thing, look at this picture, it's my bundle size analyze
, it's not so much, but maybe  if you had time to decrease package size would be nice 

![image](https://user-images.githubusercontent.com/6206777/75239824-9904c300-57d8-11ea-9e67-1627d4e4e783.png)

**Comment by sanjayV** [comment]
@gmareater 
Please create separate issue for **package size issue** and close this if it's working for you.
