### ISSUE TITLE
autoSlide not working

### ISSUE THREAD

**Issue by bobpf** [sanjayV/ng-image-slider#38]
Looks like a really cool component!  Thanks!

Setting autoSlide to true (also tried 1 as the documentation is a bit fuzzy) and infinite to true... but I cannot get the images to auto slide.  Here is a snapshow of my NgImageSliderComponent properties...  Strange thing is if I mouse over the images it does animate to the next slide automatically.  Any help would greatly be appreciated.
{ cdRef: 
   { _view: 
      { def: [Object],
        parent: [Object],
        viewContainerParent: null,
        parentNodeDef: [Object],
        context: [Circular],
        component: [Circular],
        nodes: [Object],
        state: 1036,
        root: [Object],
        renderer: [Object],
        oldValues: [Object],
        disposables: null,
        initIndex: -1 },
     _viewContainerRef: null,
     _appRef: null },
  platformId: 'browser',
  imageSliderService: {},
  elRef: { nativeElement: {} },
  sliderMainDivWidth: 478,
  imageParentDivWidth: 2500,
  imageObj: 
   [ { image: 'assets/slideshow/Brent Murphy 037.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 037.jpg',
       alt: 'foo',
       title: 'foo',
       index: 3 },
     { image: 'assets/slideshow/Brent_Murphy_017.jpg',
       thumbImage: 'assets/slideshow/Brent_Murphy_017.jpg',
       alt: 'alt',
       title: 'foo title',
       index: 0 },
     { image: 'assets/slideshow/Brent Murphy 018.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 018.jpg',
       alt: 'foo',
       title: 'foo',
       index: 1 },
     { image: 'assets/slideshow/Brent Murphy 036.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 036.jpg',
       alt: 'foo',
       title: 'foo',
       index: 2 },
     { image: 'assets/slideshow/Brent Murphy 037.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 037.jpg',
       alt: 'foo',
       title: 'foo',
       index: 3 } ],
  ligthboxImageObj: 
   [ { image: 'assets/slideshow/Brent_Murphy_017.jpg',
       thumbImage: 'assets/slideshow/Brent_Murphy_017.jpg',
       alt: 'alt',
       title: 'foo title',
       index: 0 },
     { image: 'assets/slideshow/Brent Murphy 018.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 018.jpg',
       alt: 'foo',
       title: 'foo',
       index: 1 },
     { image: 'assets/slideshow/Brent Murphy 036.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 036.jpg',
       alt: 'foo',
       title: 'foo',
       index: 2 },
     { image: 'assets/slideshow/Brent Murphy 037.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 037.jpg',
       alt: 'foo',
       title: 'foo',
       index: 3 } ],
  totalImages: 4,
  leftPos: -500,
  effectStyle: 'none',
  speed: 2,
  sliderPrevDisable: false,
  sliderNextDisable: false,
  slideImageCount: 1,
  sliderImageWidth: 500,
  sliderImageHeight: 375,
  sliderInnerHeight: 345,
  sliderImageSizeWithPadding: 500,
  autoSlideCount: 0,
  showArrowButton: true,
  textDirection: 'auto',
  imageMargin: 0,
  infinite: true,
  imagePopup: true,
  images: 
   [ { image: 'assets/slideshow/Brent_Murphy_017.jpg',
       thumbImage: 'assets/slideshow/Brent_Murphy_017.jpg',
       alt: 'alt',
       title: 'foo title',
       index: 0 },
     { image: 'assets/slideshow/Brent Murphy 018.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 018.jpg',
       alt: 'foo',
       title: 'foo',
       index: 1 },
     { image: 'assets/slideshow/Brent Murphy 036.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 036.jpg',
       alt: 'foo',
       title: 'foo',
       index: 2 },
     { image: 'assets/slideshow/Brent Murphy 037.jpg',
       thumbImage: 'assets/slideshow/Brent Murphy 037.jpg',
       alt: 'foo',
       title: 'foo',
       index: 3 } ],
  videoAutoPlay: false,
  paginationShow: false,
  arrowKeyMove: true,
  imageClick: 
   { _isScalar: false,
     observers: [],
     closed: false,
     isStopped: false,
     hasError: false,
     thrownError: null,
     __isAsync: false },
  arrowClick: 
   { _isScalar: false,
     observers: [],
     closed: false,
     isStopped: false,
     hasError: false,
     thrownError: null,
     __isAsync: false },
  lightboxArrowClick: 
   { _isScalar: false,
     observers: [],
     closed: false,
     isStopped: false,
     hasError: false,
     thrownError: null,
     __isAsync: false },
  currentImageTitle: '',
  ligthboxShow: false,
  activeImageIndex: 0,
  visiableImageIndex: 1,
  lightboxNextDisable: false,
  lightboxPrevDisable: false,
  showImage: true,
  sliderMain: { nativeElement: {} },
  imageDiv: 
   { nativeElement: 
      { __zone_symbol__clickfalse: [Object],
        __zone_symbol__mouseenterfalse: [Object],
        __zone_symbol__mouseleavefalse: [Object] } } }

**Comment by plinkpaste** [comment]
I have mine set like this, and autoscroll works:

```
<ng-image-slider
          [images]="images"
          [infinite]="true"
          [autoSlide]="5"
          [showArrow]="false"
          [imagePopup]="false"
          [imageSize]="{height: 100}"
        ></ng-image-slider>
```

**Comment by sanjayV** [comment]
Hi @bobpf 
here is the working example with `[autoSlide]="1"`
https://stackblitz.com/edit/angular-dep6cc?file=src%2Fapp%2Fapp.component.html
Auto slide will pause if user move mouse over image

**Comment by bobpf** [comment]
Well that is odd.  I take your code verbatim which I see working and put it into my app and it fails.  The only difference I can see is I am using Angular 8 and a newer Typescript version, but I forked your example and upgraded to the same versions and it still works.

**Comment by bobpf** [comment]
FYI,

 

I updated my application to Angular 9 to see if that would make a difference and it did not.  However, after some tinkering around I discovered that my component had a change detection of “OnPush”.  Removing this change detection strategy allow the slide show to start working again.

**Comment by sanjayV** [comment]
Hi @bobpf 

Can we close this issue if **Auto Slide** working fine for your

**Comment by bobpf** [comment]
Yes.  Thanks!
