### ISSUE TITLE
Override image size with imageSize property on each image

### ISSUE THREAD

**Issue by MrSuttonmann** [sanjayV/ng-image-slider#39]
Hello,

I would like to use your slider to display some images, however these images are not all uniform widths. They are the same height however.

I have set a default height on the component:

```lang-html
<ng-image-slider
          ...
          [imageSize]="{height: 100}"
        ></ng-image-slider>
```
... and set each image width on the image object:

```lang-json
{
      ...
      imageSize: {
        width: 200
      }
}
```

The images are still all the same width. Unless this can be fixed or support added unfortunately it seems using this slider is a deal-breaker for me.

**Comment by sanjayV** [comment]
Hi @plinkpaste 
This is happening because I am using fix width and height for  all images (whatever receive from @input `[imageSize]` or default {width: 205, height: 200}.

will it be helpful for you If I receive each image width/height from **[images] @input**
something like 
```
{
    image: 'assets/img/slider/1.jpg',
    thumbImage: 'assets/img/slider/1_min.jpeg',
    width: '200px'
    height: '315px'
}
```

OR
do you have any other suggestion?

**Comment by plinkpaste** [comment]
I like your suggestion, and that would be really useful.

I would suggest one slight change to your code though:

```
{
    image: 'assets/img/slider/1.jpg',
    thumbImage: 'assets/img/slider/1_min.jpeg',
    imageSize: {
        width: '200px'
        height: '315px'
    }
}
```

If either the height or width is undefined, then it can use the @Input imageSize or default.

**Comment by tsproesser** [comment]
Would it maybe be possible to keep the aspect ratio? Just set the height and get the correspondending with.

**Comment by WTIGER001** [comment]
Has this option been implemented yet? It would be very useful for my project and is the only reason that I cannot use it right now.

**Comment by MrSuttonmann** [comment]
@sanjayV I am no longer requiring this change as I have since changed employment, however it seems there are others interested. Do you have any update for them? Many thanks.

**Comment by pavanteja90** [comment]
@sanjayV, any update on this? I would love to have this as all of my images are of different sizes as well.
