### ISSUE TITLE
Image is not loading on Viewer

### ISSUE THREAD

**Issue by hysnyasir** [sanjayV/ng-image-slider#4]

**Comment by hysnyasir** [comment]
When open image in a Viewer and click on the next or previous button its not loading the image only show the loader. And when we minimize the browser and open it. its show the image. Please let me know what I am missing.

**Comment by sanjayV** [comment]
Hi @hysnyasir 
can you provide your code snippet, so I can verify what exact issue you are facing.

**Comment by hysnyasir** [comment]
Its very simple
<ng-image-slider [images]="imageObject" #nav></ng-image-slider>

ts code:
imageObject: SliderHotelImageModel[] = [];

export class SliderHotelImageModel extends BaseModel {   
    image: string;
    thumbImage: string;

    constructor() {
		super();
        this.image = '';
        this.thumbImage = '';
    }
}

**Comment by sanjayRanosys** [comment]
I am using same code in my [demo](https://ng-image-slider.herokuapp.com/)
but not facing such issues as you mentioned

can you share full code of your component

**Comment by sanjayV** [comment]
I am using same code in my [demo](https://ng-image-slider.herokuapp.com/)
but not facing such issues as you mentioned

can you share full code of your component

**Comment by hysnyasir** [comment]
Here is the component code:
import { NgForm, FormControl } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { SpinnerButtonOptions } from './../../../../partials/content/general/spinner-button/button-options.interface';
import { Component,
	OnInit,
	Input,
	Output,
	ChangeDetectionStrategy,
	ChangeDetectorRef,
	NgZone,
	ViewChild,
	Inject } from '@angular/core';
import { NgbPopover } from '@ng-bootstrap/ng-bootstrap';
import { NgbPopoverConfig } from '@ng-bootstrap/ng-bootstrap';
import { OfferService } from '../../../../../core/services/offer/offer.service';
import { FlashSaleClaimCampaignDetailModel } from '../../../../../core/models/flashsalepartner/FlashSaleClaimCampaignDetail.model';
import { SliderHotelImageModel } from '../../../../../core/models/flashsalepartner/SliderHotelImage.model';
import { OfferModel } from '../../../../../core/models/campaigns/offer.model';
import { _MatSlideToggleMixinBase, MatDialog, MatDialogRef, MAT_DIALOG_DATA, MatTable, MatStepper } from '@angular/material';
import { isDate, isNumber } from 'util';
import { TokenStorage } from '../../../../../core/auth/token-storage.service';

@Component({
    selector: 'm-preview-offer',
    templateUrl: './preview-offer.dialog.component.html',
    styleUrls: ['./preview-offer.dialog.component.scss'],
  })
export class PreviewOfferComponent implements OnInit {
	public _flashSalesPartnerClaimCampaignModel: FlashSaleClaimCampaignDetailModel = new FlashSaleClaimCampaignDetailModel();

	private _displayedOffersColumns: string[] = ['checkInOut', 'allotments', 'roomType', 'netRate', 'mealType'];

	@ViewChild('offersTable')
	private _offersTable: MatTable<OfferModel>;

    private _errors: string[] = [];
	public loading = false;
	private _userId: number;
	public isAcceptTermsAndCondition: boolean = false;
	public promotionDate: Date;

	private _minDateStart = new Date();
	private _minDateEnd = new Date(); //

	viewLoading: boolean = false;
	loadingAfterSubmit: boolean = false;

    spinner: SpinnerButtonOptions = {
		active: false,
		spinnerSize: 18,
		raised: true,
		buttonColor: 'primary',
		spinnerColor: 'accent',
		fullWidth: false
	};

	imageObject: SliderHotelImageModel[] = [];

    constructor(private _route: ActivatedRoute,
                private _router: Router,
				private _offerService: OfferService,
				private _tokenStorage: TokenStorage,
                private _changeDetectorRef: ChangeDetectorRef,
                _zone: NgZone) {
    }

    ngOnInit(): void {
		this._route.queryParams.subscribe(params => {
			const id = params.id;
			 this._offerService.GetFlashSaleCampaignDetail(id).subscribe( result => {
			 debugger;
			 this._flashSalesPartnerClaimCampaignModel = result;
			 this.imageObject = result.sliderHotelImage;
			 this._offersTable.renderRows();
			 this._changeDetectorRef.detectChanges();
		 } );
		});
		this._userId = this._tokenStorage.getUserId();
    }

	/* Actions */
	imageClickTest() {
		debugger;
	}
	arrowClickTest() {
		debugger;
	}
	
	goBack(id = 0) {
		const _backUrl = 'flashsalepartnersdashboard';
		this._router.navigateByUrl(_backUrl);
	}

    onClaimOfferClick(form: NgForm) {

    }

    showError():  boolean {
        return 0 !== this._errors.length;
    }

	onAcceptTermsAndConditions(value) {

	}
    /* Properties */

	get FlashSalesPartnerClaimCampaign(): FlashSaleClaimCampaignDetailModel {
		return this._flashSalesPartnerClaimCampaignModel;
	}

    get offers(): OfferModel[] {
		return this._flashSalesPartnerClaimCampaignModel.offers;
	}
	get DisplayedOffersColumns(): string[] {
		return this._displayedOffersColumns;
	}
    get Errors(): string[] {
        return this._errors;
    }
    get Spinner(): any {
        return this.spinner;
	}

	get MinDateStart(): any {
		return this._minDateStart;
	}
	get MinDateEnd(): any {
		return this._minDateEnd;
	}

	get CurrencySign(): string {
		return this._flashSalesPartnerClaimCampaignModel.currencyCode;
	}

}

**Comment by sanjayV** [comment]
@hysnyasir I checked with your code, It's working perfectly for me.
It would be good if you create a demo on stackblitz,  where we can identify issue.

**Comment by hysnyasir** [comment]
I think its due to its not updating the changes and we need to call "_changeDetectorRef.detectChanges();" on next or previous. Can you please provide me event on both buttons?

**Comment by hysnyasir** [comment]
We are using Angular 6

**Comment by sanjayV** [comment]
Hi @hysnyasir 
I just updated package version to 1.2.2 according requirements.
Now you can handle **slider next/prev** and **lightbox-popup next/prev** arrow click events
for slider next/prev use **@output : arrowClick**
for lightbox-popup next/prev use **@output: lightboxArrowClick**

for more detail please visit ng-image-slider npm page [API Reference](https://www.npmjs.com/package/ng-image-slider#api-reference-optional-) link

**Comment by hysnyasir** [comment]
Its working.
Thanks for your support.

**Comment by hysnyasir** [comment]
Also update it in your API References :)

**Comment by sanjayV** [comment]
@hysnyasir 
I'm Closing this discussion as issue has been resolved
