### ISSUE TITLE
I dont get Close button on fullscreen

### ISSUE THREAD

**Issue by Fuat1** [sanjayV/ng-image-slider#40]
i dont get close button when i click to images what am i doing wrong ? 
Edit: Everything is included and installed on Module
template : 
```
<div style="text-align:center;">
      <ng-image-slider [images]="imageObject" #nav
        [showArrow]="false"
        slideImage="1"></ng-image-slider>
      </div>

```
ts file : 
```
imageObject: Array<object> = [{
    image: 'assets/Front-end/1.PNG',
    thumbImage: 'assets/Front-end/1.PNG',
    alt: 'alt of image',
    title: 'Dependecies of project part1'
}, {
    image: 'assets/Front-end/2.PNG', // Support base64 image
    thumbImage: 'assets/Front-end/2.PNG', // Support base64 image
    title: 'Dependecies of project part2', // Optional: You can use this key if want to show image with title
    alt: 'Image alt' // Optional: You can use this key if want to show image with alt
}
];
```
![image](https://user-images.githubusercontent.com/47986508/75042791-49b05100-54bf-11ea-81f2-a578367b4daf.png)

**Comment by sanjayV** [comment]
Hi @Fuat1 
Close button showing for image fullscreen view
working example : https://angular-dep6cc.stackblitz.io/

**Comment by Fuat1** [comment]
i have seen examples and put the exact codes on examples but that does not solve my problem, i need to know how to put it there

**Comment by sanjayV** [comment]
@Fuat1 can you verify your css.
May be your css overriding slider css.
I am using `.close` class for Close button.

**Comment by Fuat1** [comment]
can you give me example? because i could not find any css close example

**Comment by sanjayV** [comment]
@Fuat1 Please verify that your css not using **.close** class.

**Comment by Fuat1** [comment]
how about you verify and send me some working example with code ? what a joke answers

**Comment by Fuat1** [comment]
here you go my css does this verify for you ? 
`button {
  position: fixed;
  bottom: 5px;
  right: 5px;
  font-size: 20px;
  text-align: center;
  border-radius: 5px;
  outline: none;
}

mat-card {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  border-radius: 5px; /* 5px rounded corners */
  width: initial;
  margin-left: 5px;
  margin-right: 5px;
  /* color: aliceblue; */
  background-color: rgb(0,22,40);
  margin-bottom: 5px;
  margin-top: 5px;
  color: darkgray;
  border-radius: 7%;
}

/* On mouse-over, add a deeper shadow */
mat-card:hover {
  box-shadow: 0 26px 34px 0 rgb(1, 7, 44);
}

/* Add some padding inside the card container */
img {
	position:relative;
	margin-right:12px;
	padding:5px;
	box-shadow: 0 0 0.14rem 0.07rem rgba(0, 100, 100, 0.9) !important;
	width:100px;
  height:20%;
  margin-left: 10px;
}

h2, h3, h4, h5, h6{
  margin-left: 10px;
  margin-top: 5px;
}

img:hover {
  transition: transform .2s;
  z-index: 1;
  width: 87%;
  height: initial;
  display: block;
  margin-left: auto;
  margin-right: auto;
  /* width: 50%; */
  position:absolute;
}
`

**Comment by sanjayV** [comment]
@Fuat1 
I already shared working code example with you and its showing close button for fullScreen view
https://stackblitz.com/edit/angular-dep6cc

**Comment by sanjayV** [comment]
@Fuat1 are you still facing issue with **close button**?

**Comment by Fuat1** [comment]
yeah could not fix it no matter what i did. maybe i do something wrong. anyway thanks

**Comment by ShivamShokeen** [comment]
I am also getting the same issue. I am using ionic + angular and the version of the package is `"ng-image-slider": "^2.6.4"`. Whereas on stackblitz it's working (https://stackblitz.com/edit/ng-image-slider-demo?file=src%2Fapp%2Fapp.component.html). What should  
 I do to solve this issue?

**Comment by HeroSpha** [comment]
Close button is not showing
