### ISSUE TITLE
lightboxArrowClick is not working

### ISSUE THREAD

**Issue by sergiocalero** [sanjayV/ng-image-slider#41]
Hello,
first of all, I would like to thank you for this component. It is very useful to me.
I have read the code on ng-image-slider.component.ts and it seems that lightboxArrowClick event is never thrown.

Are you planning to add this future in a short term?

Thank you in advance!

**Comment by sanjayV** [comment]
@sergiocalero 
I have fixed this issue in latest [ng-image-slider](https://www.npmjs.com/package/ng-image-slider) version

**Comment by sergiocalero** [comment]
thank you!
