### ISSUE TITLE
How to stop autoslide on hover?

### ISSUE THREAD

**Issue by sanathfp** [sanjayV/ng-image-slider#43]

**Comment by sanjayV** [comment]
@sanathfp 
autoSlide pause functionality already exist in **ng-image-slider**

You can verify it by below working example and code
https://angular-dep6cc.stackblitz.io/
https://stackblitz.com/edit/angular-dep6cc

**Comment by sanathfp** [comment]
It doesn't work on infinite scroll mode with multiple items. Is there a way to pause it?

**Comment by sanjayV** [comment]
@sanathfp 
**autoSlide pause** working on mouse hover with multiple items and infinite scroll mode.
https://angular-dep6cc.stackblitz.io/
https://stackblitz.com/edit/angular-dep6cc

**Comment by sanjayV** [comment]
@sanathfp 
can we close this issue if **autoSlide pause** working for you?
