### ISSUE TITLE
nextImage & previousImage on fullscreen works on normal slider

### ISSUE THREAD

**Issue by sergiocalero** [sanjayV/ng-image-slider#46]
Hi sanjayV,
I have notice that the available methods nextImage & previousImage work only for the normal slider,
but there are any methods for scrolling the images on full screen mode.
Are you planning to add them?
Thank you.
![2020-03-04 16_26_56-Ng Image Slider](https://user-images.githubusercontent.com/35838517/75894807-119cfc80-5e35-11ea-9fba-d2301bac5068.png)

**Comment by sanjayV** [comment]
@sergiocalero 
I have created separate [npm package for fullScreen image popup](https://www.npmjs.com/package/ng-image-fullscreen-view) and this functionality already exist here. I will use that package in **ng-image-slider** for fullScreen view.

**Comment by sergiocalero** [comment]
Ok, I will wait for the update!
