### ISSUE TITLE
is there a way to detect image pop close 

### ISSUE THREAD

**Issue by rajashekarreddy2222** [sanjayV/ng-image-slider#48]

**Comment by sanjayV** [comment]
@rajashekarreddy2222 
I have added **lightboxClose** event in [new version](https://www.npmjs.com/package/ng-image-slider#api-reference-optional-).

for more detail please visit:
https://www.npmjs.com/package/ng-image-slider#api-reference-optional-

**Comment by rajashekarreddy2222** [comment]
Thank you

**Comment by jigneshk5** [comment]
Hi @sanjayV 
I want to know if there is a way I can get the index of closed image.
I have tried this: (lightboxClose)="hideGallery($event)"
But unable get the index in $event. Please help.
