### ISSUE TITLE
[videoAutoPlay]="true" doesn't work for MP4 video files on pop up video 

### ISSUE THREAD

**Issue by hverma** [sanjayV/ng-image-slider#49]
Thanks again for such a simple but powerful image slider!

Video doesn't auto play on pop up. User have to press the play button every time. My code block below:-

<ng-image-slider [images]="imageObject"  [imageSize]="imageSize" [arrowKeyMove]="false" [animationSpeed]="0.5" [videoAutoPlay]="true" #nav></ng-image-slider>

**Comment by sanjayV** [comment]
@hverma 
I have fixed this issue in [ng-image-slider new version](https://www.npmjs.com/package/ng-image-slider)
