### ISSUE TITLE
How to set z-index for ng-image-slider-lightbox to show on top of all elements

### ISSUE THREAD

**Issue by hpardess** [sanjayV/ng-image-slider#5]
Please see the uploaded image. How to place the lightbox on top of all elements.
<img width="1274" alt="Screen Shot 1398-01-08 at 9 10 26 AM" src="https://user-images.githubusercontent.com/6196491/55130763-ba2ce180-5139-11e9-9b2f-4df6276ef89b.png">

**Comment by sanjayRanosys** [comment]
Hi @hpardess 

Just add following css in your css file
```
.ng-image-slider-lightbox {
    z-index: 999999 !important;
}
```

**Comment by sanjayV** [comment]
Hi @hpardess 
Can we close this discussion if you are able to set z-index?

**Comment by hermanwhyd** [comment]
mybe this link will help other: https://github.com/angular/components/issues/7636#issuecomment-345172877
