### ISSUE TITLE
Blobs work with images but not with Videos

### ISSUE THREAD

**Issue by hverma** [sanjayV/ng-image-slider#50]
Thanks for your great work.

Images seem to load fine. However, local videos don't load.

The link below works in other tabs but not in the slider.

{video: "blob:http://localhost:4200/23a774ab-c86d-4965-bce6-86936db479b5"}

**Comment by sanjayV** [comment]
@hverma 
**ng-image-slider** support base64 string for image and video.
I am not sure you using correct basee64 string.
Please check following working example with base64 video
https://stackblitz.com/edit/ng-image-slider-video-demo

**Comment by aabdo** [comment]
Thanks for your efforts,
I have the same problem.
I find out that you are using the file extension the determine the type of the file (image, youtube video, or mp4 video), but when we use a blob URL that doesn't afford file extension example: "blob:http://localhost:4200/23a774ab-c86d-4965-bce6-86936db479b5" the Url is classified as Image Url.
can you change the source code of "setUrl" Methode and use "this.isVideo" property to determine if it's a video or image link.
Best regards.
