### ISSUE TITLE
using pagination buttons does not update properly the index numbers

### ISSUE THREAD

**Issue by sergiocalero** [sanjayV/ng-image-slider#52]
I have enabled the pagination (paginationShow). Using the buttons to move forward and backward the images, index of the images does not follow the normal sequence.
For example, if I have 5 images, first click shows the second image, but the pagination subtitle shows: 1 of 5, instead of 2 of five.
Thank you in advance!
Kind regards!

**Comment by sanjayV** [comment]
@sergiocalero 
I have fixed this issue in [new version](https://www.npmjs.com/package/ng-image-slider)
