### ISSUE TITLE
Is it possible to get the swipe event (slide left/right in mobile/touch)?

### ISSUE THREAD

**Issue by luizdanielmlima** [sanjayV/ng-image-slider#53]
Hello,

    Thank you for your support. I´m using your component in a Angular 8 project. Below the image-slider I´m showing a div with some dynamic text (html) corresponding to each image of the slider. I can currently change it when my custom prev/next buttons are clicked, but I also need to do it when the user swipes left/right on his smartphone. Is there any @Output event from the slider where I can get this events? 

Thank you in advance!

**Comment by sanjayV** [comment]
apologies for delayed response....
here is the working example with swipe event : https://angular-ivy-lnafx2.stackblitz.io/
