### ISSUE TITLE
youtube video is not playing in lightbox

### ISSUE THREAD

**Issue by mohanve7** [sanjayV/ng-image-slider#54]
After clicking on the slider thumbnail of a youtube video, its showing just image of the video instead of playing it in lightbox popup.
![Screenshot (183)](https://user-images.githubusercontent.com/49280708/78456862-f3d8e680-76c3-11ea-8bf5-3f45c7031ec4.png)

**Comment by DMalagonH** [comment]
I have the same issue

**Comment by sanjayV** [comment]
@mohanve7 @DMalagonH 
Can you send me value that you passing in `[images]`.
working example with **youtube** and **mp4** videos: https://stackblitz.com/edit/ng-image-slider-video-demo

**Comment by DMalagonH** [comment]
Hi @sanjayV, actually I used the same example from the documentation

`{
       video: 'https://youtu.be/6pxRHBw-k8M' // Youtube url
 }
`

**Comment by sanjayV** [comment]
@DMalagonH @mohanve7 
Can you check with same values that I am using in below **stackblitz** example
[https://stackblitz.com/edit/ng-image-slider-video-demo](https://stackblitz.com/edit/ng-image-slider-video-demo)

**Comment by sanjayV** [comment]
@DMalagonH @mohanve7 
can we close this issue if you are able to play video in lightbox popup?

**Comment by yasemindogan93** [comment]
Issue is still not fixed btw.
