### ISSUE TITLE
How show only one image full width?

### ISSUE THREAD

**Issue by sbeka** [sanjayV/ng-image-slider#56]
How show only one image full width?

![image](https://user-images.githubusercontent.com/12037904/79076634-82311600-7d1d-11ea-82d7-0020873cee95.png)

**Comment by sanjayV** [comment]
@sbeka 
There are two ways to show single image
1. You can set same width of `<ng-image-slider>` parent element, that you provided to `<ng-image-slider>` image. By this way it will display only one image of slider.
2. You can set `imageSize` property  `[imageSize]="{width: '100%'}`. It will get `<ng-image-slider>` parent element width and set it to slider image width.

working example: [https://stackblitz.com/edit/ng-image-slider-demo-2](https://stackblitz.com/edit/ng-image-slider-demo-2?file=src%2Fapp%2Fapp.component.html)

**Comment by sbeka** [comment]
thank you!
