### ISSUE TITLE
Not able to display the mp4 video url in ng-image-slider

### ISSUE THREAD

**Issue by pavankishorekaranth** [sanjayV/ng-image-slider#58]
Hi Sanjay,

Need your help on this.

This is the url : https://xyz/SampleVideo1.mp4?sp=r&st=2020-04-18T15:17:34Z&se=2020-04-18T23:17:34Z&spr=https&sv=2019-02-02&sr=b&sig=bxDE7%2BYIrauqQN%2BPJZB2iqnkCQOMmMLQkBhXecxZXwM%3D

The url will be in this format. After extension what we have is sas token for privacy. It is not considering as mp4 in ng-image-slider component

**Comment by sanjayV** [comment]
@pavankishorekaranth 
I have fixed this issue [ng-image-slider new version](https://www.npmjs.com/package/ng-image-slider).

**Comment by pavankishorekaranth** [comment]
Thanks sanjay 🙂👍
