### ISSUE TITLE
Is it possible to set border radius of image to 0?

### ISSUE THREAD

**Issue by Svathna** [sanjayV/ng-image-slider#60]

**Comment by sanjayV** [comment]
@Svathna 
you can override **ng-image-slider** css by your own css
```
.ng-image-slider .ng-image-slider-container .main .main-inner .img-div img {
    border-radius: 0;
}
```

**Comment by Svathna** [comment]
> @Svathna
> you can override **ng-image-slider** css by your own css
> 
> ```
> .ng-image-slider .ng-image-slider-container .main .main-inner .img-div img {
>     border-radius: 0;
> }
> ```

i just try it and i still can not set border radius to 0

**Comment by sanjayV** [comment]
@Svathna 
Please find working example, here I am enable to set `border-radius: 0`
https://stackblitz.com/edit/angular-rpxf84?embed=1&file=src/app/app.component.ts

**Comment by Svathna** [comment]
`encapsulation: ViewEncapsulation.None`
Now it work thanks , the things is becuz of i missing this line that why.

**Comment by rodrigofbm** [comment]
`ViewEncapsulation.None` broke a lot of css. Would be nice if we get something like 
`<ng-image-slider [border-radius]="0"> </ng-image-slider>`
