### ISSUE TITLE
disable imagePopup but keep imageClick output event

### ISSUE THREAD

**Issue by HaimDX** [sanjayV/ng-image-slider#64]
Hello,
For now, if you want to listen to the capture imageClick output event you have to enable imagePopup. Is there any possibility to bypass that as I don't want to show the popup but I would still want to react on image click ?

**Comment by sanjayV** [comment]
@HaimDX 
**imageClick** event is not depended on **imagePopup**.
You can still get click event value in Output **imageClick** if **imagePopup** is set as false.
working example: https://stackblitz.com/edit/angular-ng-image-slider-events?embed=1&file=src/app/app.component.html&hideExplorer=1

**Comment by Nikesh-hub** [comment]
How we can set cursor : pointer ?

**Comment by sanjayV** [comment]
@Nikesh-hub You can use you own custom css.
working example: https://stackblitz.com/edit/angular-ng-image-slider-events?embed=1&file=src/app/app.component.html
