### ISSUE TITLE
Add active class on selected image thumbnail in the slide

### ISSUE THREAD

**Issue by TheCoderFish** [sanjayV/ng-image-slider#65]
I am using the slider as a child component and when clicked the image is preview on a view above the slider (not in a popup).So i wanted to highlight the user which image is selected by adding a border around the slider thumbnail.

**Comment by sanjayV** [comment]
@TheCoderFish 

Added this feature in [ng-image-slider new version](https://www.npmjs.com/package/ng-image-slider)
Now it will add class **selected-image** on image div, after click on image.
You can add your own custom css using this class.

Here is working example: https://stackblitz.com/edit/angular-ng-image-slider-events?embed=1&file=src/app/app.component.css

**Comment by TheCoderFish** [comment]
hey , thank you so much for the upgrade.

**Comment by chuckinator85** [comment]
I am attempting to utilize this new feature and am not having much luck. I updated to the newest version of the module and can see the class being applied when I click on an image, but I am not seeing the custom styling applied. I am not sure how this works or if you need to see my code to assist:

My component CSS:

ng-image-slider .custom-image-main img {
    border-radius: 0 !important;
}

ng-image-slider .img-div.selected-image {
    border: 3px solid red;
    box-sizing: border-box;
}

My component HTML:

<mat-step formArrayName="tickets" *ngFor="let ticket of orderForm.get('tickets').controls; let i = index;">
      <div [formGroupName]="i">
        <ng-template matStepLabel>{{ 'Ticket ' + (i + 1) }}</ng-template>
        <div fxLayout="row wrap" style="margin-top: 50px;">
          <div fxFlex.gt-md="55" fxFlex="45">
            <mat-form-field>
              <mat-label>Select Collection</mat-label>
              <mat-select name="collection" formControlName="collection" (ngModelChange)="this.selectCollection($event)">
                <mat-option *ngFor="let collection of this.eventsService.selectedEvent.collections" [value]="collection.id">{{ collection.name }}</mat-option>
              </mat-select>
            </mat-form-field>
            <ng-image-slider #nav [images]="this.collectionItems" [imagePopup]="false" [infinite]="false" [autoSlide]="1" [imageSize]="{width: 250, height: 250}" (imageClick)="this.selectItem($event)"></ng-image-slider>
          </div>
          <div fxFlex.gt-md="5" fxFlex="10"></div>
          <div fxFlex.gt-md="40" fxFlex="45">
            <mat-form-field>
              <input matInput placeholder="First Name" formControlName="firstName">
            </mat-form-field>
            <mat-form-field>
              <input matInput placeholder="Last Name" formControlName="lastName">
            </mat-form-field>
          </div>
        </div>
        <div style="margin-top: 30px;">
          <button mat-raised-button color="accent" matStepperPrevious>Back</button>
          <button mat-raised-button color="warn" matStepperNext>Next</button>
        </div>
      </div>
    </mat-step>
    <mat-step>
      <ng-template matStepLabel>Transaction Details</ng-template>
      <div>
        <button mat-raised-button color="accent" matStepperPrevious>Back</button>
      </div>
    </mat-step>

![Capture](https://user-images.githubusercontent.com/48659730/88566946-c6ae9c00-d004-11ea-8d5b-eb0a8300f45c.PNG)

**Comment by sanjayV** [comment]
@chuckinator85 
Here is the working example: https://stackblitz.com/edit/angular-ng-image-slider-events?embed=1
Make sure you are using `encapsulation: ViewEncapsulation.None` in ts file
![Screenshot from 2020-07-28 08-40-27](https://user-images.githubusercontent.com/2578736/88903749-c7983580-d271-11ea-9508-f8906ab0d814.png)

**Comment by chuckinator85** [comment]
I greatly appreciate the help, I was missing the encapsulation piece, it is
now working as expected.

Thanks,

Charles

**Comment by chuckinator85** [comment]
I do have two ideas on how this could be improved from a usage standpoint.
If a user clicks on the same picture, the styling would be removed instead
of it only moving when a different picture is selected. For the second,
would be if the picture array is cleared out or updated with new values,
the styling is also removed. In my use case I am using your module to
display a set of pictures, that a user can then click on to select which
one they want and information about it is displayed. Currently, if a user
selects a different grouping of pictures, the style is persistent and shows
up on the new element in that same index. Not the end of the world, but
would likely result in a cleaner user experience.

Thanks,

Charles
