### ISSUE TITLE
Going to previous page while lightbox is open freeze the scroll navigation.

### ISSUE THREAD

**Issue by Socrapop** [sanjayV/ng-image-slider#68]
Dear Sanjay Verma,

### How to reproduce the bug :

- Inside an app, navigate to a page with ng-image-slider. Open the lightbox. Click "Previous page" button on the browser or "Return" button on a mobile phone.
- The page is still frozen and scroll navigation is disabled. 
- The user have to refresh the page / close the app to fix it.

### What I'm thinking
I'm kinda new to Angular, but in `ng-image-slider.component.ts`, [line 409](https://github.com/sanjayV/ng-image-slider/blob/11fcc1d175c70481d153aac3ea616be89533d0b1/projects/ng-image-slider/src/lib/ng-image-slider.component.ts#L409), `showlightbox()` is changing the body element to overflow hidden. And the `close()` function removes this.

I don't know if it's possible to call a function on `ngOnDestroy()`, but calling the `close()` function at that time could fix it I think.

EDIT: 
Ok so I tried to set `this.elRef.nativeElement.ownerDocument.body.style.overflow = "";` in my page on `ngOnDestroy()` and I fixed the issue. So I think the above solution is right.
I will make a new pull-request.

Have a nice day :)

**Comment by sanjayV** [comment]
Thanks @Socrapop for PR

I have merged it.
