### ISSUE TITLE
Event when image changes

### ISSUE THREAD

**Issue by ajdinahmetovic** [sanjayV/ng-image-slider#7]
Is there an event that is triggered whenever image changes in slider so I can do other stuff on image change ?

**Comment by sanjayV** [comment]
Yes, you can use **arrowClick** event
It will return you event name (**next** / **previous**)

for more detail please visit:
https://www.npmjs.com/package/ng-image-slider#api-reference-optional-

**Comment by ajdinahmetovic** [comment]
Thanks a lot for quick response it worksss ! <3
