### ISSUE TITLE
How to NOT stop autoslide on hover?

### ISSUE THREAD

**Issue by Kenan-Hussein** [sanjayV/ng-image-slider#70]
Can make autoslide not stop on hover ?

Thanks in advance

**Comment by sanjayV** [comment]
@Kenan-Hussein 
Just published [ng-image-slider](https://www.npmjs.com/package/ng-image-slider) new version
Now autoslide will work even on mouse hover if you pass *autoSlide* value as like: `{interval: 2, stopOnHover: false}`

```
<ng-image-slider
      #nav
      [images]="imageObject"
      [autoSlide]="{interval: 2, stopOnHover: false}"`
></ng-image-slider>
```
