### ISSUE TITLE
How can use with SSR?

### ISSUE THREAD

**Issue by AndrewReal0** [sanjayV/ng-image-slider#76]
I like this lib, but neet use with a Angular proyect SSR, how can make it?

**Comment by shafqatjan** [comment]
its the same method, im using it

**Comment by sanjayV** [comment]
@AndrewReal0 
There is no any additional requirement to use **ng-image-slider** with SSR.
You can take reference from this github repo
https://github.com/keshavkhatri/angular8-with-ssr
