### ISSUE TITLE
getting error with angular 6

### ISSUE THREAD

**Issue by Nikesh-hub** [sanjayV/ng-image-slider#79]
node_modules/ng-image-slider/lib/ng-image-slider.component.d.ts(34,9): error TS1086: An accessor cannot be declared in an ambient context
node_modules/ng-image-slider/lib/slider-lightbox/slider-lightbox.component.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by sanjayV** [comment]
For angular version 8 or less, use `"skipLibCheck": true` in `tsconfig.json` for prevent **ambient context** issue.
```js
"compilerOptions": {
    "skipLibCheck": true
}
```
