### ISSUE TITLE
not Supporting in ng-version="7.2.11"

### ISSUE THREAD

**Issue by sashissd** [sanjayV/ng-image-slider#8]
HI Sanjay,
Thank you for this library . I tried to use this code in Angular 7 and the images are not displaying in browser.But its working in ng-version="6.1.10" . Could you please tell me will it work in Angular 7? or am I missing something.

**Comment by sanjayV** [comment]
Hi @sashissd 
I check **ng-image-slider** with Angular 7. It's working perfectly.
You just need to fix images path issue.
Put all images into asset folder (that provided by default by Angular CLI in **/src** folder) and set image path like  `assets/image1.jpg`
OR
If you using another folder for store image then you need figure out how to include image
You can take reference from https://stackoverflow.com/questions/53431905/can-angular-serve-images-outside-assets-folder#answer-53432121

**Comment by sashissd** [comment]
I Just used the youtube links. when you had in the example  and its not working but when I click  , the pop up is loading the image or videos

**Comment by sanjayV** [comment]
@sashissd 
can you provide your code snippet, so I can verify what exact issue you are facing.

**Comment by sashissd** [comment]
Its some style sheet error in my code which is blocking the images . Its working as expected 

Thank you
