### ISSUE TITLE
Feature Request: Output event for slide change

### ISSUE THREAD

**Issue by PhilippSoehnlein** [sanjayV/ng-image-slider#82]
I do my own navigation-buttons for the slider and want to also implement a disabled state for them. For exampke, when the slider is on the first position, I want to have the button for the previous slide to be disabled. When `[arrowKeyMove]` is set to true, I can't update my disabled state, when the keyboard is used to navigate, because there's no event I can listen to.

So, what do think about a `(navigate)`-Output or something similar?

**Comment by sanjayV** [comment]
apologies for delayed response..
here is the working example https://stackblitz.com/edit/angular-ivy-lnafx2?file=package.json
