### ISSUE TITLE
Second image show in first slider

### ISSUE THREAD

**Issue by niklat22** [sanjayV/ng-image-slider#95]
If any property use to set second image in first in slider?

![imageedit_2_7537676603](https://user-images.githubusercontent.com/46586998/101235151-edd05500-36eb-11eb-99e6-1d17ad42668f.jpg)

**Comment by bojjakaseenadhreddy** [comment]
Hi niklat22, 
I made changes to solve this issue. 
Please check at #96 .
Let me know if you need further information.

**Comment by niklat22** [comment]
Thanks @bojjakaseenadhreddy it's working.
